[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
  command = "yarn build && cd functions/node-fetch && yarn"
  functions = "functions"
  publish = "dist"
  
[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"
